apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my.fullname" . }}
  labels:
{{ include "my.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    volumes:
        - name: shared-volume
          cephfs:
            monitors:
            - {{ .Values.cephfs.monitors.monitor1 }}:{{ .Values.cephfs.monitors.port }}
            - {{ .Values.cephfs.monitors.monitor2 }}:{{ .Values.cephfs.monitors.port }}
            - {{ .Values.cephfs.monitors.monitor3 }}:{{ .Values.cephfs.monitors.port }}
            user: {{ .Values.cephfs.userName }}
            secretRef:
              name: {{ .Values.cephfs.secretName }}
            readOnly: false
    containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: URL
            value: "{{ .Values.spring.datasource.url }}"
          volumeMounts:
          - mountPath: "/data/"
            name: shared-volume
                 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
