# Default values for my.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alec/my 
  tag: v1 
  pullPolicy: IfNotPresent
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres_demo

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
