apiVersion: v1
kind: Service
metadata:
  name: {{ include "my.fullname" . }}
  labels:
{{ include "my.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    # to have a nodeport for exposint the service outside with Altair:30000/department
      {{ if and .Values.service.type  ( eq .Values.service.type "NodePort" ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "my.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
