# Default values for my.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alec/my 
  tag: v2 
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080
  nodePort: 30000

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.78:5432/postgres_demo
nodeSelector: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tolerations: []

affinity: {}
